//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int User_id { get; set; }
        [Required(ErrorMessage = "Please enter first name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please enter Last name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please enter Email")]
        public string Email { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        [Required(ErrorMessage = "Please enter your Gender")]
        public string Gender { get; set; }
        public string Image { get; set; }
        [Required(ErrorMessage = "Please select image ")]
        public Nullable<System.DateTime> Birthdate { get; set; }
        [Required(ErrorMessage = "Please enter your password")]
        public string Password { get; set; }
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Upload File")]
        [Required(ErrorMessage = "Please choose file to upload.")]
        public string file { get; set; }
    }
}
